version: '3'
services:
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MARIADB_USER=my_cool_user
      - MARIADB_PASSWORD=my_cool_secret
      - MARIADB_ROOT_PASSWORD=my-secret-pw
      - MARIADB_DATABASE=booking_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
