server:
  servlet.context-path: /booking-service
  port: 8080

#spring boot actuator properties:
management:
  server.port: 8081
  endpoints:
    web.exposure.include: '*'
    web.base-path: /
  endpoint.health.show-details: always

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/booking_db?createDatabaseIfNotExist=true
    username: my_cool_user
    password: my_cool_secret
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    properties.hibernate:
      show_sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-current.xml

aerospike:
  hosts: localhost:3000
  namespace: booking-service
  operations:
    maxAttempts: 5
    backoff:
      delay: 3
      multiplier: 2

booking.camel.kafka:
  default.brokerList: localhost:29092
  producer:
    booking-history:
      brokerList: ${booking.camel.kafka.default.brokerList}
      topicName: booking_history
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
    booking-history:
      brokerList: ${booking.camel.kafka.default.brokerList}
      topicName: booking_history
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      autoCommitEnable: true
      groupId: ${spring.application.name}
      autoOffsetReset: earliest
      consumersCount: 4
